import type { Metadata } from "next";
import {Poppins, Roboto_Mono, Crimson_Text, Gravitas_One} from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
  variable: "--font-poppins"
})
const roboto = Roboto_Mono({
  subsets: ['latin'],
  weight: '700',
  variable: "--font-roboto"
})
const crimson = Crimson_Text({
  subsets: ['latin'],
  weight: '600',
  variable: "--font-crimson"
})
const gravitas = Gravitas_One({
  subsets: ['latin'],
  weight: '400',
  variable: "--font-gravitas"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} ${crimson.variable} ${gravitas.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}